### ISSUE TITLE
GDM without Coordinates

### ISSUE THREAD

**Issue by Leitemfa** [fitzLab-AL/gdm#10]
Hello, I would like to perform GDM, but my data comes from a designed experiment so the geographical distance do not provide much information. Therefore, I would like to know if it is possible to apply GDM without adding this information.

Thanks in advance

**Comment by jamiemkass** [comment]
I believe that spatial distance is not necessary -- you just need one or
more variables to calculate distances relating to the differences in these
variables between locations. If you measured some variable at these
locations, you can use them to calculate a distance matrix.

Jamie

**Comment by Leitemfa** [comment]
Thanks for the reply. In that case I can add it and then set geo = F, right?

Thanks again,
Marcio

**Comment by jamiemkass** [comment]
Yes, I believe so, but the authors of the package can confirm.

**Comment by fitzLab-AL** [comment]
@Leitemfa @jamiemkass is correct. You can simply set geo=F as long as you have at least one other environmental variable for model fitting.
