### ISSUE TITLE
Problem with  gdm.varImp function

### ISSUE THREAD

**Issue by burbrink** [fitzLab-AL/gdm#12]
Hello,

I am using the latest CRAN version of GDM (v. 1.4.2.2) and I am able to run the gdm function on my data and the results look reasonable.

However, I keep getting this error when running gdm.varImp:

modTest_b <- gdm.varImp(gdm_sitepair, fullModelOnly = F, geo=T, nPerm=100, parallel=F,splines=rep(3,13))
Error in data[, 3] - data[, 5] : non-numeric argument to binary operator

I realize that asking for a solution without details of the input data is a bit nebulous.

Therefore, I have attached the data that can be read in with dget(gdm_sitepair.txt)->gdm.varImp.txt

Advice would be really appreciated!

Thanks so much for any help!

Frank

[gdm_sitepair.txt](https://github.com/fitzLab-AL/GDM/files/6273174/gdm_sitepair.txt)

**Comment by fitzLab-AL** [comment]
Responded via email: error was related to the name of one of the input variables, which contained a "$".
