### ISSUE TITLE
Non-default splines argument breaks isplineExtract()

### ISSUE THREAD

**Issue by sponslerdb** [fitzLab-AL/gdm#13]
The original `isplineExtract()` function is hardcoded for the default of 3 splines per variable.  The problem is in this line of the function definition:

    xDat[,i] <-  seq(from=model$knots[[(i*3)-2]],to=model$knots[[(i*3)]], length=PSAMPLE)

And it can be fixed with:

    xDat[,i] <-  seq(from=model$knots[[(i*numsplines)-(numsplines-1)]],to=model$knots[[(i*numsplines)]], length=PSAMPLE)

**Comment by fitzLab-AL** [comment]
Thanks for the fix. Edit will appear in upcoming release.
