### ISSUE TITLE
Specifying non-equal spline numbers across variables breaks plot() and isplineExtract()

### ISSUE THREAD

**Issue by sponslerdb** [fitzLab-AL/gdm#14]
When I specify non-equal numbers of splines for the variables in my model, the model call itself seems to run correctly, but both plot() and isplineExtract() throw "subscript out of bounds" errors. I would presume this is because these functions are expecting equal dimensions across variables and then trying to access rows that don't exist.  

`gdm_WN6 <- gdm(sitepair_WN, geo = FALSE, splines = c(6, 4, 5, 6, 6))`

`plot(gdm_WN6)`

```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'plot': subscript out of bounds
```

**Comment by fitzLab-AL** [comment]
Yes, that would be a problem. I will look into a fix.

**Comment by fitzLab-AL** [comment]
@sponslerdb I think I have fixed these issues, but let me know if you run into problems.
