### ISSUE TITLE
plotUncertainty(): more documentation, custom plotting method

### ISSUE THREAD

**Issue by sponslerdb** [fitzLab-AL/gdm#16]
A couple notes on plotUncertainty():

1. After reading the documentation, I'm still a bit unclear on exactly how exactly it works and how I would explain it in a paper. Could the documentation on this command be elaborated a bit?
2.  I use isplineExtract() to tabulate splines for custom plotting, but there does not seem to be any corresponding method for extract the results of plotUncertainty() for custom plotting. This would be nice.

**Comment by fitzLab-AL** [comment]
@sponslerdb added more detail to description and option to function to save result to disk.
