### ISSUE TITLE
Consider forcing user to specify spline number

### ISSUE THREAD

**Issue by sponslerdb** [fitzLab-AL/gdm#17]
I have found that the results of a GDM can be very sensitive to spline number (supplied in the `splines` argument), and I would suggest that future versions of `gdm()` require users to supply the `splines` argument to avoid false confidence in the default settings.  

Along the same lines, it would be helpful to include some means of comparing models of different complexity to decide what the spline number should be. Ferrier et al. (2007) suggest such procedures, albeit vaguely:

"The predictors included in a model, and the number of I-spline basis  functions  employed  for  each  predictor  (controlling  the allowable  complexity  of  the  nonlinear  transformation  of  that predictor), can be determined using various automated selection strategies,  including  forward-selection,  backward-elimination,  and stepwise  procedures."

**Comment by fitzLab-AL** [comment]
@sponslerdb the default number of splines is 3, which is the minimum value possible - adding more than 3 splines only increases model complexity, which may not be warranted. It makes sense to start with the default value of 3 and then increase from there as needed. 

That said, one should think about (and ideally test) whether the increased complexity is really necessary.  I haven't explored the issue much, but when I have, I have found that adding more than three splines typically leads to only minor increases in deviance explained & not much more in the way of inference. YMMV.

As your second comment alludes to, the right way to do it would be to test whether adding splines leads to significant improvements in deviance explained and/or changes in variable importance. That would require adding permutation tests like that already implemented in the variable importance / selection function. As currently implemented, that function is VERY slow & adding the additional burden of testing different number of splines would only make things a lot worse. Perhaps one day we will get around to improving that function & implementing such tests, but I don't foresee tackling this anytime soon.
