### ISSUE TITLE
Installation error on Ubuntu 20.04 with R 4.1.3

### ISSUE THREAD

**Issue by fsdias** [fitzLab-AL/gdm#19]
Hi,
I'm running Ubuntu 20.04 and R 4.1.3 and I'm getting this installation error. I also tried `devtools::install_github("fitzLab-AL/gdm")` with the same result.
```
install.packages("gdm")
Installing package into ‘/home/fd/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/gdm_1.5.0-1.tar.gz'
Content type 'application/x-gzip' length 688341 bytes (672 KB)
==================================================
downloaded 672 KB

* installing *source* package ‘gdm’ ...
** package ‘gdm’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/lib/R/site-library/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-lENDSu/r-base-4.1.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Gdmlib.cpp -o Gdmlib.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/lib/R/site-library/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-lENDSu/r-base-4.1.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Message.cpp -o Message.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/lib/R/site-library/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-lENDSu/r-base-4.1.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c NNLSDoubleCore.cpp -o NNLSDoubleCore.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/lib/R/site-library/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-lENDSu/r-base-4.1.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c NNLS_Double.cpp -o NNLS_Double.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/lib/R/site-library/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-lENDSu/r-base-4.1.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c dllmain.cpp -o dllmain.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/usr/lib/R/site-library/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-lENDSu/r-base-4.1.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c registerDynamicSymbol.c -o registerDynamicSymbol.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/lib/R/site-library/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-lENDSu/r-base-4.1.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c stdafx.cpp -o stdafx.o
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o gdm.so Gdmlib.o Message.o NNLSDoubleCore.o NNLS_Double.o dllmain.o registerDynamicSymbol.o stdafx.o -L/usr/lib/R/lib -lR
installing to /home/fd/R/x86_64-pc-linux-gnu-library/4.1/00LOCK-gdm/00new/gdm/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
double free or corruption (out)
Aborted (core dumped)
ERROR: lazy loading failed for package ‘gdm’
* removing ‘/home/fd/R/x86_64-pc-linux-gnu-library/4.1/gdm’
Warning in install.packages :
  installation of package ‘gdm’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpfbOcEj/downloaded_packages’
```

**Comment by fitzLab-AL** [comment]
I suspect this is an issue with the machine on which you are installing the package & not an issue with the package itself.

**Comment by fsdias** [comment]
I reinstalled R and removed all R packages. I tried to install "gdm" and still got the same error message.

**Comment by jarioksa** [comment]
The error comes from byte-compiling of the package, and hints to a problem in R. Compilation and installation of **gdm** looks fine till you start byte-compiling its **R** code.

**Comment by fitzLab-AL** [comment]
@jarioksa Thanks for your message. I am more of an ecologist than a computer scientist / programmer, so I am not certain I completely follow what the problem is. Is this something related to the gdm package itself - or with how it is being installed? I suppose I am asking whether this is a problem I can (and should) fix or not?

**Comment by fsdias** [comment]
I solved this issue by:

- purging all GDAL related packages from my system and by disabling all repositories that provide GDAL related packages
- Running `sudo aptitude install libgdal-dev `(say "N" to the first suggestion and "Y" to the second one)
- `sudo apt-get install libgdal-dev`
- Open RStudio and install `terra` and `raster` which will be compiled
- Install "gdm"

Using any packages from "http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu" will prevent this solution from working. After "gdm" is installed the user can delete  "raster" and "terra" using RStudio and install them from the above mentioned ppa:  `sudo apt-get install r-cran-terra r-cran-raster`

Removing `libgdal-dev` does not prevent `gdm `from working. It seems to be required for installation only.

**Comment by fsdias** [comment]
This issue is a bit a corner case, but the solution I found might be useful to someone else. However, this is definitely not a bug.

If you agree I can close this issue and add this solution to the README.md of this repository via pull request.
