### ISSUE TITLE
Possible bug in gdm.varImp

### ISSUE THREAD

**Issue by grcolli** [fitzLab-AL/gdm#26]
Hello,
gdm.varImp() is returning the following error message:

"Fitting initial model with all 18 predictors...
Sum of I-spline coefficients for predictors(s) Geographic = 0Sum of I-spline coefficients for predictors(s) t.mean = 0Sum of I-spline coefficients for predictors(s) t.max = 0
Removing predictor(s) Geographic and proceeding with permutation testing...Removing predictor(s) t.mean and proceeding with permutation testing...Removing predictor(s) t.max and proceeding with permutation testing...
Error in `[.data.frame`(spTable, c(7:(6 + nVars))) : 
  undefined columns selected"

Used this function before with no issues. Any hints? Thanks a lot!

**Comment by fitzLab-AL** [comment]
Sorry, but I will need some more information to help isolate the issue. There have been numerous updates to this function recently.

**Comment by zdiazmar** [comment]
Hi there,

I am having the same issue with the gdm.varImp() function. I am trying to run a GDM using genomic data and climate data and geo=T. However, I am noticing that 'Sum of coefficients for Geographic: 0' meaning geographic distance has no effect on genetic turnover (see attached). Is it possible that this variable in not being removed? Please let me know what other data I can provide! Thanks
[gdm.bio.isp.fit.csv](https://github.com/fitzLab-AL/gdm/files/9601153/gdm.bio.isp.fit.csv)

**Comment by fitzLab-AL** [comment]
Can you confirm that you are using the latest version of the package?

**Comment by zdiazmar** [comment]
I am using gdm_1.5.0-3 and R version 4.0.2

**Comment by fitzLab-AL** [comment]
Please update to the latest version on github, which I believe will fix this issue.

**Comment by zdiazmar** [comment]
Thanks - that solved the issue!
