### ISSUE TITLE
predict error

### ISSUE THREAD

**Issue by willright28** [fitzLab-AL/gdm#28]
Hi @fitzLab-AL @mliskAL 

I would like to make some predictions but got an error.
 I used two sets of factors in my gdm model,1) 19 bioclimate factors(original value) and 2) land cover data(range from 0~1). When I tried to make a prediction through time the result only had zero value, I checked whether this was brought out by having the same raster layer(i.e. climate or land cover not change) for the two time periods stack but the answer was not. 
I've had no problems with the gdm model using 19 bioclimate factors in the past. So I run two models with the same response data but using only climate or land cover data, this time the predict function worked well. 
So I cannot figure out why the function produces an error result when the two sets of factors are combined, they have the same resolution and extent, and different period stacks have the same order for factors.

Looking forward to your reply and thanks in advance.

**Comment by fitzLab-AL** [comment]
I am not able to explore this problem without a reproducible example.

**Comment by willright28** [comment]
Hi @fitzLab-AL 
Thanks for your reply. Here I attach a reproducible example, please take a look.

[example.zip](https://github.com/fitzLab-AL/gdm/files/9178900/example.zip)

**Comment by fitzLab-AL** [comment]
The problem is with your raster data, not the function / package. The non-bioclimatic variables have a few rows of NAs.
