### ISSUE TITLE
gdm.varimp error

### ISSUE THREAD

**Issue by jamesryan1896** [fitzLab-AL/gdm#29]
When I attempt to run gdm.varimp() I am returned with an error "Error in `[.data.frame`(x, , -c(remVarCols1, remVarCols2)) : 
  object 'remVarCols1' not found"

I have a number of datasets and for some of them the code works and for others it doesn't. The only difference is the species included in the analysis, the landscape variables are all the same for each site. I have attached an example to demonstrate the error, I hope it works! (and by that I mean I hope it gives you an error)

Thank you

**Comment by jamesryan1896** [comment]
[Example.zip](https://github.com/fitzLab-AL/gdm/files/9348329/Example.zip)

**Comment by fitzLab-AL** [comment]
I do not get any errors. Are you using the latest version of the package?

**Comment by jamesryan1896** [comment]
I am using _gdm_ version 1.5.0-3 and I have the same error for R version 4.2.1 and 4.1.2

This is a screenshot of how the error appears after I attempt to run gdm.varimp()
![error](https://user-images.githubusercontent.com/57244426/185015737-fe1a526b-2b51-4f50-be65-b8d3e562c9de.JPG)

**Comment by fitzLab-AL** [comment]
You need to update to the latest version of the package on Github.
