### ISSUE TITLE
Can you share a vignette of phylogenetic generalised dissimilarity model with gdm package?

### ISSUE THREAD

**Issue by Otoliths** [fitzLab-AL/gdm#30]
Hi, @fitzLab-AL & @mliskAL 

I have trouble running phylo-GDM, the site-by-site biological distance (dissimilarity) is either 0 or 1, how to address it?
Can gdm package implement cluster([Laffan et al., 2010](http://dx.doi.org/10.1111/j.1600-0587.2010.06237.x)) based on a Sorenson distance in [`Biodiverse`](https://github.com/shawnlaffan/biodiverse) tool?

Data: 
[Example_tree.nex](https://github.com/shawnlaffan/biodiverse/blob/master/data/Example_tree.nex)
[Example_site_data.csv](https://github.com/shawnlaffan/biodiverse/blob/master/data/Example_site_data.csv)

```
library(gdm)
library(ape)
library(tidytree)
tre <- read.nexus("Example_tree.nex")
tre$tip.label <- gsub("Genus:","",tre$tip.label)
tre_tb <- as_tibble(tre)
dt <- read.csv("Example_site_data.csv")
test <- dt %>% left_join(tre_tb[,3:4], by = c("species" = "label"))

sp <- test[,c("num","species","x", "y")]
phy <- test[,c("num","branch.length")]

exFormat <- formatsitepair(sp, bioFormat=2, siteColumn="num", XColumn="x",sppColumn = "species",
                             YColumn="y", predData=phy)

head(exFormat)
```

```
distance weights s1.xCoord s1.yCoord s2.xCoord s2.yCoord s1.branch.length s2.branch.length
1        0       1   3229628   3078198   3216986   2951192       0.07551968       0.16666667
2        0       1   3229628   3078198   3216038   2960749       0.07551968       0.07551968
3        1       1   3229628   3078198   3217265   2960874       0.07551968       0.16666667
4        1       1   3229628   3078198   3205746   2963060       0.07551968       0.07551968
5        1       1   3229628   3078198   3214891   2928147       0.07551968       0.16666667
6        1       1   3229628   3078198   3219317   2971030       0.07551968       0.03299437
```

reference
Laffan, S. W., Lubarsky, E., & Rosauer, D. F. (2010). Biodiverse, a tool for the spatial analysis of biological and related diversity. Ecography, 33(4), 643-647. [10.1111/j.1600-0587.2010.06237.x](http://dx.doi.org/10.1111/j.1600-0587.2010.06237.x)

Thank you！

Looking forward to your reply.

**Comment by fitzLab-AL** [comment]
The best I can do to help is to direct you to this publication & the associated set of examples:

https://onlinelibrary.wiley.com/doi/full/10.1111/geb.13459
