### ISSUE TITLE
predData is necessary in formatsitepair, even though the help file states it is not

### ISSUE THREAD

**Issue by leorjorge** [fitzLab-AL/gdm#4]
I'm trying to use formatsitepair to analyse the effect of two sets of distance matrices on a third one, but the formatsitepair function gives the following error:
Error in formatsitepair(bioData = In.fmt, bioFormat = 3, abundance = TRUE,  : 
  argument "predData" is missing, with no default

However, in the help of this function, distPreds is stated to be:
An optional list of distance matrices to be used as predictors, either in combination with, or as a substitute for, predData.

How am I supposed to use only distance matrices and no predData?

**Comment by fitzLab-AL** [comment]
help docs updated
