### ISSUE TITLE
Error related to unit tests

### ISSUE THREAD

**Issue by fitzLab-AL** [fitzLab-AL/gdm#44]
@rvalavi I needed to make a few minor updates to the gdm package for it to remain available on CRAN. After those updates, CRAN is reporting an error related to unit testing. You can see the CRAN check results [here](https://cran.r-project.org/web/checks/check_results_gdm.html). I also copied the output below.

Any thoughts?

checking tests ... [12s/18s] ERROR
  Running ‘tinytest.R’ [12s/18s]
Running the tests in ‘tests/tinytest.R’ failed.
Complete output:
  > 
  > if ( requireNamespace("tinytest", quietly=TRUE) ){
  +   tinytest::test_package("gdm")
  + }
  
  test_gdm.R....................    0 tests    terra 1.7.78
  
  test_gdm.R....................    0 tests    
  test_gdm.R....................    0 tests    
  test_gdm.R....................    0 tests    
  test_gdm.R....................    0 tests    
  test_gdm.R....................    1 tests  [0;32mOK [0m 
  test_gdm.R....................    1 tests  [0;32mOK [0m 
  test_gdm.R....................    2 tests  [0;31m1 fails [0m 
  test_gdm.R....................    2 tests  [0;31m1 fails [0m 
  test_gdm.R....................    2 tests  [0;31m1 fails [0m 
  test_gdm.R....................    3 tests  [0;31m2 fails [0m 
  test_gdm.R....................    3 tests  [0;31m2 fails [0m Error in h(simpleError(msg, call)) : 
    error in evaluating the argument 'x' in selecting a method for function 'global': object 'pred_raster' not found
  Calls: <Anonymous> ... eval -> eval -> <Anonymous> -> .handleSimpleError -> h
  Execution halted

**Comment by rvalavi** [comment]
Hi @fitzLab-AL 
Interesting! It seems they are all related to the prediction not being made (see the figure below). On my local checks, everything passes, but I've added a few new changes to my local version, which I've requested to be merged into the main version. Could you please merge the new pull request and try again: https://github.com/fitzLab-AL/gdm/pull/42

I believe it's crucial to include these changes before submitting to CRAN.

![image](https://github.com/user-attachments/assets/c2252dc6-54ac-407c-9ec8-54dd58925b4b)
