### ISSUE TITLE
Error in predict function

### ISSUE THREAD

**Issue by dinilu** [fitzLab-AL/gdm#46]
Hi fitzLab-AL!!
I just spoted an error in the predict function. I was trying to replicate the examples in the webpage (https://mfitzpatrick.al.umces.edu/gdm/index.html), but when you run the following chunk of code: 
```
gdm.1.pred <- predict(object=gdm.1, data=gdmTab)
head(gdm.1.pred)
plot(gdmTab$distance,
     gdm.1.pred,
     xlab="Observed dissimilarity",
     ylab="Predicted dissimilarity"
     xlim=c(0,1),
     ylim=c(0,1),
     pch=20,
     col=rgb(0,0,1,0.5))
lines(c(-1,2), c(-1,2))
```
... the resulting plot is completely different. I am not sure what the error is. At first, I thought it was reordering the results but `plot(sort(gdm.1.pred), sort(gdm.1$predicted))` do not produce a perfect line, so it seems to me that they are making different calculations.
Let me know if I can help somehow. We can be in contact also by email.
Best,
Diego

**Comment by dinilu** [comment]
It seems to be a bug introduced between versions 1.5.0-9.1 and 1.6.0-1: 

- Versions 1.5.0-1, 1.5.0-3, and 1.5.0-9.1 works. 
- Versions 1.6.0-1 and 1.6.0-2 doesn't work.

I hope this helps!

**Comment by rvalavi** [comment]
Hi @dinilu, I already noticed and fixed the bug, and it will be resolved when the changes are pulled to this repo.
Thank you for reporting.

**Comment by fitzLab-AL** [comment]
Thanks @rvalavi! I will pull the changes. For the most recent version submitted to CRAN (1.6.0-2), I am still getting errors from CRAN associated with the test script - see here:

https://cran.r-project.org/web/checks/check_results_gdm.html

**Comment by rvalavi** [comment]
Hi @fitzLab-AL, I checked in both linux and windows and it's fine for me. I assume the errors come from permisson issues in those linux falvors. I added a couple of changes to the test files (here: https://github.com/fitzLab-AL/gdm/pull/48). Please try merging the changes and give it another test.

**Comment by rvalavi** [comment]
Hi @dinilu , could you please re-install the package and try again?

**Comment by dinilu** [comment]
Yes! I confirm that the current version in GitHub works well.
