### ISSUE TITLE
error in formatsiterepair function 'aggregation function missing: defaulting to length'

### ISSUE THREAD

**Issue by anwar79melb** [fitzLab-AL/gdm#8]
I followed the same code used in vignette (https://github.com/fitzLab-AL/GDM/blob/master/vignettes/gdmVignette.pdf) for `formatsiterepair()`. Although my data structure was exactly similar to that used in the vignette. My dataset has about 6000 rows. Using 1000 rows don't give any error. There is not NA values in my dataset. Any solution please?

`> gdmTab <- formatsitepair(sppTab, bioFormat = 2, siteColumn = "site", XColumn = "Long", YColumn = "Lat", sppColumn = "grasshopper", predData = envTab)
Aggregation function missing: defaulting to length
Error in createsitepair(dist = distData, spdata = bioData, envInfo = predData,  : 
  The length of distance values are not the same as the expected number of rows of the site-pair table, unable to proceed.
In addition: Warning message:
In formatsitepair(sppTab, bioFormat = 2, siteColumn = "site", XColumn = "Long",  :
  No abundance column specified, assuming species data are presence`

**Comment by Tai-Rocha** [comment]
I  have a similar error, and my dataset also exactly a vignette... I still trying to fix this...

`Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.data.frame': The length of distance values is not the same as the expected number of rows in the site-pair table, unable to proceed.`

**Comment by anwar79melb** [comment]
Hi,

Make sure that your data doesn't have any NA. The gdm package cannot handle
NA.

Cheers,
Anwar

**Comment by Tai-Rocha** [comment]
Thanks for the response @anwar79melb ! I am sure that my data does not have NA .

Cheers
Tainá

**Comment by anwar79melb** [comment]
Then, possibly check data structure in each column to make sure they are
all numeric. For example, 'str(dataframe$columnName)'.

Thanks.

**Comment by Tai-Rocha** [comment]
I have 2 inputs as dataframe: 
1- bioData (4 columns):  species name, site's ids, Longitude and Latitude.  
2- predData (26 columns): site's ids and 25 columns of environmental values. 
When I verify my  predData input except for the site's ids column (that is an integer) all columns of environmental values are numeric.
However, I had an idea to change the predData dataframe for raster stack and this is work now!!

**Comment by Tai-Rocha** [comment]
I have 2 inputs as dataframe: 
1- bioData (4 columns):  species name, site's ids, Longitude and Latitude.  

2- predData (26 columns): site's ids and 25 columns of environmental values. 

when I verify my  predData input except for the site's ids column (that is an integer) all columns of environmental values are numeric .


However, I had an idea to change the predData dataframe for raster stack and this is work now!!

Curiously via raster stack the result of this function is dataframe with many NAs that I remove with tidyverse functions (%>% drop_na()  ). Finally, I run gdm function and everything works!

Thank you so much for this help!

**Comment by anwar79melb** [comment]
All good then. Enjoy!!

Part of the credit should go to github's function to reply from email. This
is early morning here in Australia and I was replying from bed.

Regards,
Anwar
