### ISSUE TITLE
par(ask=TRUE) will improve plot.gdm

### ISSUE THREAD

**Issue by jamiemkass** [fitzLab-AL/gdm#9]
It took me a while to figure out that the plots of predictor variable splines with `plot.gdm()` were done sequentially, and that I had to press BACK in RStudio to find them. A more intuitive way would be if `plot.gdm()` set `par(ask=TRUE)` before plotting to allow users to click through the plots, then `par(ask=FALSE)` to turn it off at the end.

**Comment by fitzLab-AL** [comment]
Great suggestion. Will be added to next release.
